# Generated by Django 2.2 on 2019-04-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotpic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pic', models.ImageField(upload_to='hotpic')),
                ('index', models.IntegerField(unique=True)),
            ],
        ),
    ]
