# Generated by Django 2.2 on 2019-04-29 06:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('booksys', '0002_hotpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtitle', models.CharField(max_length=20)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
